import type { WaterObject } from "./types"

export const waterObjects: WaterObject[] = [
  {
    id: "1",
    name: "Озеро Балхаш",
    region: "Алматинская область",
    resourceType: "lake",
    waterType: "saline",
    hasFauna: true,
    passportDate: "2024-03-12",
    condition: 3,
    priority: "medium",
    coordinates: { lat: 46.1, lng: 74.0 },
    position: { x: 58, y: 34 },
    image: "/kushkakul-lake-jizzakh-green-nature.jpg",
  },
  {
    id: "2",
    name: "Озеро Алаколь",
    region: "Алматинская область",
    resourceType: "lake",
    waterType: "saline",
    hasFauna: true,
    passportDate: "2023-11-05",
    condition: 2,
    priority: "low",
    coordinates: { lat: 46.2, lng: 81.6 },
    position: { x: 78, y: 30 },
    image: "/aydar-lake-desert-uzbekistan.jpg",
  },
  {
    id: "3",
    name: "Маркаколь",
    region: "Восточно-Казахстанская область",
    resourceType: "lake",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2024-01-28",
    condition: 2,
    priority: "low",
    coordinates: { lat: 48.7, lng: 85.7 },
    position: { x: 88, y: 18 },
    image: "/charvak-reservoir-mountains-blue-water.jpg",
  },
  {
    id: "4",
    name: "Водохранилище Капчагай",
    region: "Алматинская область",
    resourceType: "reservoir",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2024-04-18",
    condition: 4,
    priority: "high",
    coordinates: { lat: 43.85, lng: 77.16 },
    position: { x: 66, y: 42 },
    image: "/andijan-reservoir-dam-water.jpg",
  },
  {
    id: "5",
    name: "Водохранилище Бухтарма",
    region: "Восточно-Казахстанская область",
    resourceType: "reservoir",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2023-09-07",
    condition: 3,
    priority: "medium",
    coordinates: { lat: 49.6, lng: 83.0 },
    position: { x: 82, y: 16 },
    image: "/kampyrkalin-reservoir-blue-water.jpg",
  },
  {
    id: "6",
    name: "Озеро Тенгиз",
    region: "Акмолинская область",
    resourceType: "lake",
    waterType: "saline",
    hasFauna: false,
    passportDate: "2023-12-15",
    condition: 5,
    priority: "high",
    coordinates: { lat: 50.5, lng: 69.3 },
    position: { x: 48, y: 18 },
    image: "/aral-sea-dried-ships-desert.jpg",
  },
  {
    id: "7",
    name: "Канал Иртыш-Караганда",
    region: "Карагандинская область",
    resourceType: "canal",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2024-02-02",
    condition: 1,
    priority: "low",
    coordinates: { lat: 49.8, lng: 73.1 },
    position: { x: 55, y: 22 },
    image: "/fergana-canal-irrigation-water.jpg",
  },
  {
    id: "8",
    name: "Канал Аrys-Туркестан",
    region: "Туркестанская область",
    resourceType: "canal",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2024-05-30",
    condition: 2,
    priority: "low",
    coordinates: { lat: 42.5, lng: 69.0 },
    position: { x: 48, y: 60 },
    image: "/amu-darya-river-khorezm.jpg",
  },
  {
    id: "9",
    name: "Шардара",
    region: "Туркестанская область",
    resourceType: "reservoir",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2024-06-18",
    condition: 4,
    priority: "high",
    coordinates: { lat: 41.3, lng: 68.3 },
    position: { x: 44, y: 70 },
    image: "/surkhan-reservoir-mountains-green.jpg",
  },
  {
    id: "10",
    name: "Озеро Сасыкколь",
    region: "Алматинская область",
    resourceType: "lake",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2023-10-21",
    condition: 3,
    priority: "medium",
    coordinates: { lat: 45.5, lng: 78.5 },
    position: { x: 69, y: 32 },
    image: "/tudakul-reservoir-dried-lake.jpg",
  },
  {
    id: "11",
    name: "Озеро Иссык",
    region: "Алматинская область",
    resourceType: "lake",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2024-07-05",
    condition: 1,
    priority: "low",
    coordinates: { lat: 43.35, lng: 77.17 },
    position: { x: 66, y: 48 },
    image: "/charvak-reservoir-mountains-blue-water.jpg",
  },
  {
    id: "12",
    name: "Саумалколь",
    region: "Северо-Казахстанская область",
    resourceType: "lake",
    waterType: "fresh",
    hasFauna: true,
    passportDate: "2023-08-19",
    condition: 2,
    priority: "low",
    coordinates: { lat: 53.2, lng: 69.6 },
    position: { x: 49, y: 10 },
    image: "/kushkakul-lake-jizzakh-region-green-nature-birds.jpg",
  },
]
